/*
 * led_button_control.c
 *
 *  Created on: Aug 8, 2025
 *      Author: Shivaprasad
 */


#include <stdint.h>
#include <stdio.h>
#include"stm32f401xx.h"
#define LOW DISABLE
void delay(void) {
	for (uint32_t i = 0; i < 500000; i++);
}
int main (void){
	GPIO_HANDLE_t GPIO_LED,GPIO_BUTTON;

	GPIO_LED.pGPIOx=GPIOA;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_NUMBER=GPIO_PIN_NO_5;
    GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_MODE=GPIO_MODE_OUT;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_SPEED=GPIO_OP_VHSP;
	GPIO_LED.GPIO_PINCONFIG.GPIO_OUTPUT_TYPE=GPIO_OP_TYPE_PP;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PULLUP_PULLDOWN=GPIO_PIN_NO_PUPD;

	GPIO_PeriClKCtrl(GPIOA,ENABLE);
	GPIO_Init(&GPIO_LED);

	GPIO_BUTTON.pGPIOx=GPIOC;
	GPIO_BUTTON.GPIO_PINCONFIG.GPIO_PIN_NUMBER=GPIO_PIN_NO_13;
	GPIO_BUTTON.GPIO_PINCONFIG.GPIO_PIN_MODE=GPIO_MODE_IN;
	GPIO_BUTTON.GPIO_PINCONFIG.GPIO_PIN_SPEED=GPIO_OP_VHSP;
	GPIO_BUTTON.GPIO_PINCONFIG.GPIO_PIN_SPEED=GPIO_PIN_NO_PUPD;
	GPIO_PeriClKCtrl(GPIOC,ENABLE);
	GPIO_Init(&GPIO_BUTTON);


	while (1) {
		if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13)==LOW)
		{

			delay();
			GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5); // Toggle PA5
		}
	}

}
