/*
 * 001led_toggle.c
 *
 *  Created on: Aug 5, 2025
 *      Author: Shivaprasad
 */


#include <stdint.h>
#include <stdio.h>
#include"stm32f401xx.h"
int main (void){
	GPIO_HANDLE_t GPIO_LED;
	GPIO_LED.pGPIOx=GPIOA;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_NUMBER=GPIO_PIN_NO_5;

	GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_MODE=GPIO_MODE_OUT;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PIN_SPEED=GPIO_OP_HSP;
	GPIO_LED.GPIO_PINCONFIG.GPIO_OUTPUT_TYPE=GPIO_OP_TYPE_PP;
	GPIO_LED.GPIO_PINCONFIG.GPIO_PULLUP_PULLDOWN=GPIO_PIN_NO_PUPD;

	GPIO_PeriClKCtrl(GPIOA, ENABLE);
	GPIO_Init(&GPIO_LED);
	return 0;

}



